export const LerfterImage = 'https://i.ibb.co/2WjpgM2/Lefter.png'
export const Ears =[
        {value : "1", label:"ACUATIC CARDS" , isDisabled:true  ,img:"https://i.ibb.co/4MTf6P9/Nimo.png"},
         {value: "Nimo2" ,label:"Nimo" ,img:"https://i.ibb.co/4MTf6P9/Nimo.png"},
         {value:"Tiny_Fan",label:"Tiny Fan" ,img:"https://i.ibb.co/G3x04sz/Tiny-Fan.png"},
         {value:"Bubblemaker",label:"Bubblemaker",img:"https://i.ibb.co/DwCkHpd/Bubblemaker.png"},
         {value:"Seaslug",label:"Seaslug",img:"https://i.ibb.co/MDsm4Kz/Seaslug.png"},
         {value:"Gill",label:"Gill",img:"https://i.ibb.co/z2Xb48n/Gill.png"},
         {value:"Inkling",label:"Inkling",img:"https://i.ibb.co/3BRt2PC/Inkling.png"},
         {value : "2", label:"PLANT CARDS" , isDisabled:true,img:"https://i.ibb.co/4MTf6P9/Nimo.png"},
         {value: "Rosa" ,label:"Rosa" ,img:"https://i.ibb.co/31PLgdk/Rosa.png"},
         {value:"Hollow",label:"Hollow",img:"https://i.ibb.co/LdN5J3F/Hollow.png"},
         {value:"Lotus",label:"Lotus",img:"https://i.ibb.co/d0Z3D2k/Lotus.png"},
         {value:"Leafy",label:"Leafy",img:"https://i.ibb.co/3SptjCj/Leafy.png"},
         {value:"Clover",label:"Clover",img:"https://i.ibb.co/tJmTMX9/Clover.png"},
         {value:"Sakura",label:"Sakura",img:"https://i.ibb.co/7WQK29D/Sakura.png"},
         {value : "3", label:"BUG CARDS" , isDisabled:true,img:"https://i.ibb.co/4MTf6P9/Nimo.png"},
         {value: "Earwing" ,label:"Earwing" ,img:"https://i.ibb.co/kJ64fgD/Earwing.png"},
         {value:"Leaf_Bug",label:"Leaf Bug",img:"https://i.ibb.co/f4Km3Cj/Leaf-Bug.png"},
         {value:"Larva",label:"Larva",img:"https://i.ibb.co/0BjkDCM/Larva.png"},
         {value:"Tassels",label:"Tassels",img:"https://i.ibb.co/PZHTTYT/Tassels.png"},
         {value:"Ear_Breathing",label:"Ear Breathing",img:"https://i.ibb.co/F3wZrQY/Ear-Breathing.png"},
         {value:"Bettle_Spike",label:"Bettle Spike",img:"https://i.ibb.co/VNf3Cnm/Bettle-Spike.png"},
         {value : "4", label:"BEAST CARDS" , isDisabled:true,img:"https://i.ibb.co/4MTf6P9/Nimo.png"},
         {value: "Nyan" ,label:"Nyan" ,img:"https://i.ibb.co/SBFMKfD/Nyan.png"},
         {value:"Innocent_Lamb",label:"Innocent Lamb",img:"https://i.ibb.co/Ph23xzV/Innocent-Lamb.png"},
         {value:"Nut_Cracker3",label:"Nut Cracker",img:"https://i.ibb.co/3dwHGJc/Nut-Cracker.png"},
         {value:"Puppy",label:"Puppy",img:"https://i.ibb.co/0mpPnF5/Puppy.png"},
         {value:"Zen",label:"Zen",img:"https://i.ibb.co/hy0dpNc/Zen.png"},
         {value:"Belieber",label:"Belieber",img:"https://i.ibb.co/2gDLZn9/Belieber.png"},
         {value : "5", label:"BIRD CARDS" , isDisabled:true,img:"https://i.ibb.co/4MTf6P9/Nimo.png"},
         {value: "Peace_Maker" ,label:"Peace Maker",img:"https://i.ibb.co/vXPKydr/Peace-Maker.png" },
         {value:"Early_Bird",label:"Early Bird ",img:"https://i.ibb.co/B3Mvn3V/Early-Bird.png"},
         {value:"Risky_Bird",label:"Risky Bird",img:"https://i.ibb.co/0G2cywz/Risky-Bird.png"},
         {value:"Little_Owl1",label:"Little Owl",img:"https://i.ibb.co/xH5n6Cg/Little-Owl.png"},
         {value:"Pink_Cheek",label:"Pink Cheek",img:"https://i.ibb.co/3sKNjBK/Pink-Cheek.png"},
         {value:"Curly",label:"Curly",img:"https://i.ibb.co/18v4gyr/Curly.png"},
         {value : "6", label:"REPTILE CARDS" , isDisabled:true,img:"https://i.ibb.co/4MTf6P9/Nimo.png"},
         {value: "Friezard" ,label:"Friezard",img:"https://i.ibb.co/Bs8Rmwm/Friezard.png" },
         {value:"Sidebarb",label:"Sidebarb",img:"https://i.ibb.co/tCw2Rzj/Sidebarb.png"},
         {value:"Swirl",label:"Swirl",img:"https://i.ibb.co/GMGsCF4/Swirl.png"},
         {value:"Curved_Spine",label:"Curved Spine",img:"https://i.ibb.co/GkhP0V8/Curved-Spine.png"},
         {value:"Pagona",label:"Pagona",img:"https://i.ibb.co/rQYckQR/Pagona.png"},
         {value:"Small_Frill",label:"Small Frill",img:"https://i.ibb.co/kQTtXzn/Small-Frill.png"},

      ];

 export const Eyes =[
         {value:"0" ,label:"ACUATIC CARDS", isDisabled:true,img:"https://i.ibb.co/4MTf6P9/Nimo.png"},
         {value: "Sleepless" ,label:"Sleepless", img:"https://i.ibb.co/GHY2sTZ/Sleepless.png"},
         {value: "Gero" ,label:"Gero", img:"https://i.ibb.co/rx3BrBN/Gero.png"},            
         {value: "Clear", label:"Clear", img:"https://i.ibb.co/Ct4Xqk4/Clear.png"},
         {value:"Telescope",label:"Telescope", img:"https://i.ibb.co/xL4500C/Telescope.png"},
         {value : "1", label:"PLANT CARDS" , isDisabled:true,img:"https://i.ibb.co/4MTf6P9/Nimo.png"},
         {value: "Papi" ,label:"Papi" , img:"https://i.ibb.co/QbqkYcw/Papi.png"},
         {value:"Confused",label:"Confused", img:"https://i.ibb.co/94XqW07/Confused.png"},
         {value:"Cucumber_Slice",label:"Cucumber Slice", img:"https://i.ibb.co/KLfPsmZ/Cucumber-Slice.png"},
         {value:"Blossom",label:"Blossom ", img:"https://i.ibb.co/gt3rHvC/Blossom.png"},
         {value : "3", label:"BUG CARDS" , isDisabled:true,img:"https://i.ibb.co/4MTf6P9/Nimo.png"},
         {value: "Kotaro" ,label:"Kotaro" , img:"https://i.ibb.co/yqs5nV6/Kotaro.png"},
         {value:"Neo",label:"Neo" , img:"https://i.ibb.co/9sxc4Kt/Neo.png"},
         {value:"Bookworm",label:"Bookworm", img:"https://i.ibb.co/qRc86ww/Bookworm.png"},
         {value:"Nerdy",label:"Nerdy ", img:"https://i.ibb.co/0VrDz7W/Nerdy.png"},
         {value : "4", label:"BEAST CARDS" , isDisabled:true,img:"https://i.ibb.co/4MTf6P9/Nimo.png"},
         {value: "Puppy" ,label:"Puppy", img:"https://i.ibb.co/52KwbdR/Puppy.png" },
         {value:"Little_Peas",label:"Little Peas", img:"https://i.ibb.co/4jr2MXv/Little-Peas.png"},
         {value:"Chubby",label:"Chubby", img:"https://i.ibb.co/Kbgptdn/Chubby.png"},
         {value:"Zeal",label:"Zeal ", img:"https://i.ibb.co/WtnpMm3/Zeal.png"},
         {value : "5", label:"BIRD CARDS" , isDisabled:true,img:"https://i.ibb.co/4MTf6P9/Nimo.png"},
        {value: "Robin" ,label:"Robin" , img:"https://i.ibb.co/Gc32PXD/Robin.png"},
        {value:"Mavis",label:"Mavis", img:"https://i.ibb.co/jkVhJNw/Mavis.png"},
         {value:"Little_Owl",label:"Little Owl", img:"https://i.ibb.co/xfVN5QD/Little-Owl.png"},
         {value:"Lucas",label:"Lucas ", img:"https://i.ibb.co/26nBb2R/Lucas.png"},
         {value : "6", label:"REPTILE CARDS" , isDisabled:true,img:"https://i.ibb.co/4MTf6P9/Nimo.png"},
         {value: "Scar" ,label:"Scar" , img:"https://i.ibb.co/mHrqy8v/Scar.png"},
         {value:"Topaz",label:"Topaz", img:"https://i.ibb.co/C2JpfJ1/Topaz.png"},
         {value:"Tricky",label:"Tricky", img:"https://i.ibb.co/WgC11zw/Tricky.png"},
         {value:"Gecko",label:"Gecko ", img:"https://i.ibb.co/3CxXcGL/Gecko.png"},
        

      ];

 export const Mouth =[
   {value:"1", label:"ACUATIC CARDS", isDisabled:true,img:"https://i.ibb.co/4MTf6P9/Nimo.png"},
   {value:"Lam", label:"Lam", img:"https://i.ibb.co/G7KRvCc/Lam.png"},
   {value:"Risky_Fish", label:"Risky Fish", img:'https://i.ibb.co/5kpht6C/Risky-fish.png'},
   {value:"Piranha", label:"Piranha", img:'https://i.ibb.co/QKTMQQ8/Piranha.png'},
   {value:"Catfish", label:"Catfish", img:"https://i.ibb.co/S7GfZKC/Catfish.png"},
   {value:"2", label:"PLANT CARDS", isDisabled:true,img:"https://i.ibb.co/4MTf6P9/Nimo.png"},
   {value:"Serious", label:"Serious", img:"https://i.ibb.co/2PbV1rX/Serious.png"},
   {value:"Zigzag", label:"Zigzag", img:"https://i.ibb.co/MRJkTDJ/Zigzag.png"},
   {value:"Herbivore", label:"Herbivore", img:"https://i.ibb.co/DgQbkDp/Herbivore.png"},
   {value:"Silence_Whisper", label:"Silence Whisper", img:"https://i.ibb.co/P5g6x66/Silence-Whisper.png"},
   {value:"3", label:"BUG CARDS", isDisabled:true,img:"https://i.ibb.co/4MTf6P9/Nimo.png"},
   {value:"Mosquito", label:"Mosquito", img:"https://i.ibb.co/tBL7BJh/Mosquito.png"},
   {value:"Cute_Bunny", label:"Cute Bunny", img:"https://i.ibb.co/vdfkTrG/Cute-Bunny.png"},
   {value:"Pincer", label:"Pincer" , img:"https://i.ibb.co/YND5mKT/Pincer.png"},
   {value:"Square_Teeth", label:"Square Teeth" , img:"https://i.ibb.co/y0rdHHZ/Square-Teeth.png"},
   {value:"4", label:"BEAST CARDS", isDisabled:true,img:"https://i.ibb.co/4MTf6P9/Nimo.png"},
   {value:"Goda", label:"Goda", img:"https://i.ibb.co/p4y4gqc/Goda.png"},
   {value:"Axie_Kiss", label:"Axie Kiss", img:"https://i.ibb.co/HFC1Qxg/Axie-Kiss.png"},
   {value:"Confident", label:"Confident", img:"https://i.ibb.co/y0J38W7/Confident.png"},
   {value:"Nut_Cracker4", label:"Nut Cracker", img:"https://i.ibb.co/g6Hf9J4/Nut-Cracker.png"},
   {value:"5", label:"BIRD CARDS", isDisabled:true,img:"https://i.ibb.co/4MTf6P9/Nimo.png"},
   {value:"Little_Owl2", label:"Little Owl", img:"https://i.ibb.co/dj6nj9Y/Little-Owl.png"},
   {value:"Doubletalk", label:"Doubletalk", img:"https://i.ibb.co/JdvyHzR/Doubletalk.png"},
   {value:"Hungry_Bird", label:"Hungry Bird", img:"https://i.ibb.co/G0b1Hmm/Hungry-Bird.png"},
   {value:"Peace_Maker2", label:"Peace Maker", img:"https://i.ibb.co/sq792fp/Peace-Maker.png"},
   {value:"6", label:"REPTILE CARDS", isDisabled:true,img:"https://i.ibb.co/4MTf6P9/Nimo.png"},
   {value:"Kotaro", label:"Kotaro", img:"https://i.ibb.co/xCbmCXt/Kotaro.png"},
   {value:"Tiny_Turtle", label:"Tiny Turtle", img:"https://i.ibb.co/ggYnsJJ/Tiny-Turtle.png"},
   {value:"Razor_Bite", label:"Razor Bite", img:"https://i.ibb.co/m6qcn2C/Razor-Bite.png"},
   {value:"Toothless_Bite", label:"Toothless Bite", img:"https://i.ibb.co/W0Q5T5C/Toothless-Bite.png"},

        ];

 export const Back =[
   {value:"1", label:"ACUATIC CARDS" ,isDisabled:true,img:"https://i.ibb.co/4MTf6P9/Nimo.png"},
   {value:"Anemone",label:"Anemone", img:"https://i.ibb.co/d5Y6xB2/Anemone.png"},
   {value:"Perch",label:"Perch", img:"https://i.ibb.co/7R972mw/Perch.png"},
   {value:"Sponge",label:"Sponge", img:"https://i.ibb.co/5Rfdm9h/Sponge.png"},
   {value:"Blue_Moon",label:"Blue Moon", img:"https://i.ibb.co/y62pTkn/Blue-moon.png"},
   {value:"Hermit",label:"Hermit", img:"https://i.ibb.co/vLQGGgm/Hermit.png"},
   {value:"Goldfish",label:"Goldfish", img:"https://i.ibb.co/55qR2B0/Goldfish.png"},
   {value:"2", label:"PLANT CARDS" ,isDisabled:true,img:"https://i.ibb.co/4MTf6P9/Nimo.png"},
   {value:"Turnip",label:"Turnip", img:"https://i.ibb.co/QJnnyFn/Turnip.png"},
   {value:"Shiitake",label:"Shiitake", img:"https://i.ibb.co/zmF1d4n/Shiitake.png"},
   {value:"Mint",label:"Mint", img:"https://i.ibb.co/Cm9LYtZ/Mint.png"},
   {value:"Pumpkin",label:"Pumpkin", img:"https://i.ibb.co/wYmxhf4/Pumpkin.png"},
   {value:"Watering_Can",label:"Watering Can", img:"https://i.ibb.co/VYfrYxF/Watering-Can.png"},
   {value:"Bidens",label:"Bidens", img:"https://i.ibb.co/TqcbQx1/Bidens.png"},
   {value:"3", label:"BUG CARDS" ,isDisabled:true,img:"https://i.ibb.co/4MTf6P9/Nimo.png"},
   {value:"Sandal",label:"Sandal", img:"https://i.ibb.co/WGr5ZJ6/Sandal.png"},
   {value:"Garish_Worm",label:"Garish Worm", img:"https://i.ibb.co/LhbX7QX/Garish-Worm.png"},
   {value:"Snail_Shell",label:"Snail Shell", img:"https://i.ibb.co/LkFDms0/Snail-Shell.png"},
   {value:"Buzz_Buzz",label:"Buzz Buzz", img:"https://i.ibb.co/V2nyJpr/Buzz-Buzz.png"},
   {value:"Scarab",label:"Scarab", img:"https://i.ibb.co/dpLvVvt/Scarab.png"},
   {value:"Spiky_Wing",label:"Spiky Wing", img:"https://i.ibb.co/WsGK9dG/Spiky-Wing.png"},
   {value:"4", label:"BEAST CARDS" ,isDisabled:true,img:"https://i.ibb.co/4MTf6P9/Nimo.png"},
   {value:"Ronin",label:"Ronin", img:"https://i.ibb.co/KFj9JDm/Ronin.png"},
   {value:"Jaguar",label:"Jaguar", img:"https://i.ibb.co/bQ9L4dG/Jaguar.png"},
   {value:"Hero",label:"Hero", img:"https://i.ibb.co/rZQxDwC/Hero.png"},
   {value:"Risky_Beast",label:"Risky Beast", img:"https://i.ibb.co/ygV7y7K/Risky-Beast.png"},
   {value:"Furball",label:"Furball", img:"https://i.ibb.co/VCFt6Wc/Furball.png"},
   {value:"Timber",label:"Timber", img:"https://i.ibb.co/pLd401h/Timber.png"},
   {value:"5", label:"BIRD CARDS" ,isDisabled:true,img:"https://i.ibb.co/4MTf6P9/Nimo.png"},
   {value:"Balloon",label:"Balloon", img:"https://i.ibb.co/sPQQvm9/Balloon.png"},
   {value:"Cupid",label:"Cupid", img:"https://i.ibb.co/C5pYWMP/Cupid.png"},
   {value:"Tri_Feather",label:"Tri Feather", img:"https://i.ibb.co/Jqr5WzK/Tri-Feather.png"},
   {value:"Kingfisher",label:"Kingfisher", img:"https://i.ibb.co/Fs0HLQq/Kingfisher.png"},
   {value:"Raven",label:"Raven", img:"https://i.ibb.co/VMMfrzQ/Raven.png"},
   {value:"Pigeon_Post",label:"Pigeon Post", img:"https://i.ibb.co/HxKFhWZ/Pigeon-Post.png"},
   {value:"6", label:"BIRD CARDS" ,isDisabled:true,img:"https://i.ibb.co/4MTf6P9/Nimo.png"},
   {value:"Croc",label:"Croc", img:"https://i.ibb.co/Qn12CRh/Croc.png"},
   {value:"Red_Ear",label:"Red Ear", img:"https://i.ibb.co/2qfbLjS/Red-Ear.png"},
   {value:"Indian_Star",label:"Indian Star", img:"https://i.ibb.co/pdT1vpx/Indian-Star.png"},
   {value:"Bone_Sail",label:"Bone Sail", img:"https://i.ibb.co/1GjTpzf/Bone-Sail.png"},
   {value:"Tri_Spikes",label:"Tri Spikes", img:"https://i.ibb.co/HxRrt43/Tri-Spikes.png"},
   {value:"Green_Thorns",label:"Green Thorns", img:"https://i.ibb.co/Vpnyr94/Green-Thorns.png"},

 ];


 export const Horn =[
  {value:"1", label:"ACUATIC CARDS" ,isDisabled:true ,img:"https://i.ibb.co/4MTf6P9/Nimo.png"},
  {value: "Anemone2",label:"Anemone", img:"https://i.ibb.co/qMtLjsB/Anemone.png"},
  {value:"Shoal_Star",label:"Shoal Star", img:"https://i.ibb.co/gWVW7Ch/Shoal-Star.png"},
  {value: "Oranda",label:"Oranda", img:"https://i.ibb.co/mvS4jkz/Oranda.png"},
  {value:"Clamshell" ,label:"Clamshell", img:"https://i.ibb.co/HYmb87d/Clamshell.png"},
  {value:"Babylonia",label:"Babylonia", img:"https://i.ibb.co/gFWNTmL/Babylonia.png"},
  { value:"Teal_Shell",label:"Teal Shell", img:"https://i.ibb.co/GQxvRZH/Teal-Shell.png"},
  {value:"2", label:"PLANT CARDS" ,isDisabled:true ,img:"https://i.ibb.co/4MTf6P9/Nimo.png"},
  {value: "Beech",label:"Beech", img:"https://i.ibb.co/YdXVKbH/Beech.png"},
  {value:"Rose_Bud",label:"Rose Bud", img:"https://i.ibb.co/vB15sQb/Rose-Bud.png"},
  {value: "Cactus",label:"Cactus", img:"https://i.ibb.co/YX4wbYD/Cactus.png"},
  {value:"Watermelon" ,label:"Watermelon", img:"https://i.ibb.co/bByvppx/Watermelon.png"},
  {value:"Strawberry_Shortcake",label:"Strawberry Shortcake", img:"https://i.ibb.co/wY9zGZq/Strawberry-Shortcake.png"},
  { value:"Bamboo_Shoot",label:"Bamboo Shoot", img:"https://i.ibb.co/Y7f6vvH/Bamboo-Shoot.png"},
  {value:"3", label:"BUG CARDS" ,isDisabled:true ,img:"https://i.ibb.co/4MTf6P9/Nimo.png"},
  {value: "Lagging",label:"Lagging", img:"https://i.ibb.co/cwyGXw6/Lagging.png"},
  {value:"Antenna",label:"Antenna", img:"https://i.ibb.co/ZfRYL31/Antenna.png"},
  {value: "Leaf_Bug2",label:"Leaf Bug", img:"https://i.ibb.co/Wz22MQp/Leaf-Bug.png"},
  {value:"Parasite" ,label:"Parasite", img:"https://i.ibb.co/d5RJ2t9/Parasite.png"},
  {value:"Pliers",label:"Pliers", img:"https://i.ibb.co/d5RJ2t9/Parasite.png"},
  { value:"Caterpillars",label:"Caterpillars", img:"https://i.ibb.co/DMWZKNy/Caterpillars.png"},
  {value:"4", label:"BEAST CARDS" ,isDisabled:true ,img:"https://i.ibb.co/4MTf6P9/Nimo.png"},
  {value: "Arco",label:"Arco", img:"https://i.ibb.co/kMrJWCX/Arco.png"},
  {value:"Dual_Blade",label:"Dual Blade", img:"https://i.ibb.co/JFF7135/Dual-Blade.png"},
  {value: "Pocky",label:"Pocky", img:"https://i.ibb.co/XxpCv5n/Pocky.png"},
  {value:"Imp" ,label:"Imp", img:"https://i.ibb.co/6JGQq92/Imp.png"},
  {value:"Merry",label:"Merry", img:"https://i.ibb.co/Qm6FHL2/Merry.png"},
  { value:"Little_Branch",label:"Little Branch", img:"https://i.ibb.co/7vZnmvC/Little-Branch.png"},
  {value:"5", label:"BIRD CARDS" ,isDisabled:true ,img:"https://i.ibb.co/4MTf6P9/Nimo.png"},
  {value: "Eggshell",label:"Eggshell", img:"https://i.ibb.co/1QmdmnN/Eggshell.png"},
  {value:"Cuckoo",label:"Cuckoo", img:"https://i.ibb.co/XspDpfZ/Cuckoo.png"},
  {value: "Trump",label:"Trump", img:"https://i.ibb.co/m8t0SYf/Trump.png"},
  {value:"Feather_Spear" ,label:"Feather Spear", img:"https://i.ibb.co/mDsHQfh/Feather-Spear.png"},
  {value:"Kestrel",label:"Kestrel", img:"https://i.ibb.co/pLWv1j7/Kestrel.png"},
  { value:"Wing_Horn",label:"Wing Horn", img:"https://i.ibb.co/Sts2b39/Wing-Horn.png"},
  {value:"6", label:"REPTILE CARDS" ,isDisabled:true ,img:"https://i.ibb.co/4MTf6P9/Nimo.png"},
  {value: "Bumpy",label:"Bumpy", img:"https://i.ibb.co/Zgf1syS/Bumpy.png"},
  {value:"Scaly_Spoon",label:"Scaly Spoon", img:"https://i.ibb.co/Myd9HrD/Scaly-Spoon.png"},
  {value: "Cerastes",label:"Cerastes", img:"https://i.ibb.co/yYDXd1c/Cerastes.png"},
  {value:"Unko" ,label:"Unko", img:"https://i.ibb.co/vc15Nhw/Unko.png"},
  {value:"Scaly_Spear",label:"Scaly Spear", img:"https://i.ibb.co/Kw8Tkzn/Scaly-Spear.png"},
  { value:"Incisor",label:"Incisor", img:"https://i.ibb.co/sQyxtPf/Incisor.png"},

        ];

export const Tail =[
   {value:"1" ,label:"ACUATIC CARDS", isDisabled:true ,img:"https://i.ibb.co/4MTf6P9/Nimo.png"},
   { value: 'Nimo' , label: ' Nimo' , img:'https://i.ibb.co/HKLGqzH/Nimo.png'},
   { value: 'Shrimp', label: ' Shrimp' , img:"https://i.ibb.co/rycC004/Shrimp.png"},           
   { value: 'Navaga', label: ' Navaga' , img:"https://i.ibb.co/j6vr90f/Navaga.png"},
   { value: 'Koi', label: ' Koi' , img:'https://i.ibb.co/Q9FbGj1/Koi.png'},
   { value: 'Tadpole', label: ' Tadpole' , img:"https://i.ibb.co/PxrtFgJ/Tadpole.png"},
   { value: 'Ranchu', label: ' Ranchu' , img:"https://i.ibb.co/svJQL9K/Ranchu.png"},
   {value:"2" ,label:"PLANT CARDS", isDisabled:true ,img:"https://i.ibb.co/4MTf6P9/Nimo.png"},
   { value: 'Cattail' , label: ' Cattail' , img:"https://i.ibb.co/pWBQjbv/Cattail.png"},
   { value: 'Hatsune', label: ' Hatsune' , img:"https://i.ibb.co/BG2n29g/Hatsume.png"},           
   { value: 'Carrot', label: ' Carrot' , img:"https://i.ibb.co/k09QM7k/Carrot.png"},
   { value: 'Yam', label: ' Yam' , img:"https://i.ibb.co/yqBGtxY/Yam.png"},
   { value: 'Potato_Leaf', label: ' Potato Leaf' , img:"https://i.ibb.co/Wfytj3b/Potato-Leaf.png"},
   { value: 'Hot_Butt', label: ' Hot Butt' , img:"https://i.ibb.co/CvhRCxq/Hot-Butt.png"},
   {value:"3" ,label:"BUG CARDS", isDisabled:true ,img:"https://i.ibb.co/4MTf6P9/Nimo.png"},
   { value: 'Fish_Snack' , label: ' Fish Snack' , img:"https://i.ibb.co/xgC31Dj/Fish-Snack.png"},
   { value: 'Ant', label: ' Ant' , img:"https://i.ibb.co/bX43vn5/Ant.png"},           
   { value: 'Pupae', label: ' Pupae' , img:"https://i.ibb.co/sW6vvWf/Pupae.png"},
   { value: 'Twin_Tail', label: ' Twin Tail', img:"https://i.ibb.co/hHrg18Q/Twin-Tail.png" },
   { value: 'Gravel_Ant', label: ' Gravel Ant' , img:"https://i.ibb.co/BG52mkR/Gravel-Ant.png"},
   { value: 'Thorny_Caterpillar', label: ' Thorny Caterpillar', img:"https://i.ibb.co/jGkcM9v/Thorny-Caterpillar.png" },
   {value:"4" ,label:"BEAST CARDS", isDisabled:true ,img:"https://i.ibb.co/4MTf6P9/Nimo.png"},
   { value: 'Nut_Cracker' , label: ' Nut Cracker', img:"https://i.ibb.co/9Z5yvPD/Nut-Cracker.png" },
   { value: 'Shiba', label: ' Shiba', img:"https://i.ibb.co/Ypb3vqK/Shiba.png" },           
   { value: 'Gerbil', label: ' Gerbil' , img:"https://i.ibb.co/3pdp2qC/Gerbil.png"},
   { value: 'Hare', label: ' Hare', img:"https://i.ibb.co/2dpqqkd/Hare.png" },
   { value: 'Rice', label: ' Rice' , img:"https://i.ibb.co/ZLvgWP7/Rice.png"},
   { value: 'Cottontail', label: ' Cottontail' , img:"https://i.ibb.co/ws0MK3k/Cottontail.png"},
   {value:"5" ,label:"BIRD CARDS", isDisabled:true ,img:"https://i.ibb.co/4MTf6P9/Nimo.png"},
   { value: 'Swallow' , label: ' Swallow' , img:"https://i.ibb.co/WkxhxLt/Swallow.png"},
   { value: 'Post_Fight', label: ' Post Fight', img:"https://i.ibb.co/XkVL2Km/Post-Fight.png" },           
   { value: 'Cloud', label: ' Cloud' , img:"https://i.ibb.co/z26Cqkd/Cloud.png"},
   { value: 'Granmas_Fan', label: ' Granmas Fan' , img:"https://i.ibb.co/KXmwLCX/Granmas-Fan.png"},
   { value: 'Feather_Fan', label: ' Feather Fan', img:"https://i.ibb.co/tpvhdvW/Feather-Fan.png" },
   { value: 'The_Last_One', label: ' The Last One', img:"https://i.ibb.co/gSgNFgC/The-Last-One.png" },
   {value:"6" ,label:"REPTILE CARDS", isDisabled:true ,img:"https://i.ibb.co/4MTf6P9/Nimo.png"},
   { value: 'Wall_Gecko' , label: ' Wall Gecko' , img:"https://i.ibb.co/fScMPn0/Wall-Gecko.png"},
   { value: 'Iguana', label: ' Iguana' , img:"https://i.ibb.co/hKwLvXn/Iguana.png"},           
   { value: 'Snake_Jar', label: ' Snake Jar' , img:"https://i.ibb.co/LCWz2FF/Snake-Jar.png"},
   { value: 'Gila', label: ' Gila' , img:"https://i.ibb.co/Z6qvpYy/Gila.png"},
   { value: 'Grass_Snake', label: ' Grass Snake' , img:"https://i.ibb.co/LPNd8k9/Grass-Snake.png"},
   { value: 'Tiny_Dino', label: ' Tiny Dino' , img:"https://i.ibb.co/RzJgPm6/Tiny-Dino.png"},
   ]


