
export const Ears =[
        {value : "1", label:"ACUATIC CARDS" , isDisabled:true},
         {value: "Nimo2" ,label:"Nimo" ,img:"https://i.ibb.co/4MTf6P9/Nimo.png"},
         {value:"Tiny_Fan",label:"Tiny Fan" ,img:"https://i.ibb.co/G3x04sz/Tiny-Fan.png"},
         {value:"Bubblemaker",label:"Bubblemaker",img:""},
         {value:"Seaslug",label:"Seaslug",img:""},
         {value:"Gill",label:"Gill",img:""},
         {value:"Inkling",label:"Inkling",img:""},
         {value : "2", label:"PLANT CARDS" , isDisabled:true},
         {value: "Rosa" ,label:"Rosa" ,img:""},
         {value:"Hollow",label:"Hollow",img:""},
         {value:"Lotus",label:"Lotus",img:""},
         {value:"Leafy",label:"Leafy",img:""},
         {value:"Clover",label:"Clover",img:""},
         {value:"Sakura",label:"Sakura",img:""},
         {value : "3", label:"BUG CARDS" , isDisabled:true},
         {value: "Earwing" ,label:"Earwing" ,img:""},
         {value:"Leaf_Bug",label:"Leaf Bug",img:""},
         {value:"Larva",label:"Larva",img:""},
         {value:"Tassels",label:"Tassels",img:""},
         {value:"Ear_Breathing",label:"Ear Breathing",img:""},
         {value:"Bettle_Spike",label:"Bettle Spike",img:""},
         {value : "4", label:"BEAST CARDS" , isDisabled:true},
         {value: "Nyan" ,label:"Nyan" ,img:""},
         {value:"Innocent_Lamb",label:"Innocent Lamb",img:""},
         {value:"Nut_Cracker3",label:"Nut Cracker",img:""},
         {value:"Puppy",label:"Puppy",img:""},
         {value:"Zen",label:"Zen",img:""},
         {value:"Belieber",label:"Belieber",img:""},
         {value : "5", label:"BIRD CARDS" , isDisabled:true},
         {value: "Peace_Maker" ,label:"Peace Maker",img:"" },
         {value:"Early_Bird",label:"Early Bird ",img:""},
         {value:"Risky_Bird",label:"Risky Bird",img:""},
         {value:"Little_Owl1",label:"Little Owl",img:""},
         {value:"Pink_Cheek",label:"Pink Cheek",img:""},
         {value:"Curly",label:"Curly",img:""},
         {value : "6", label:"REPTILE CARDS" , isDisabled:true},
         {value: "Friezard" ,label:"Friezard",img:"" },
         {value:"Sidebarb",label:"Sidebarb",img:""},
         {value:"Swirl",label:"Swirl",img:""},
         {value:"Curved_Spine",label:"Curved Spine",img:""},
         {value:"Pagona",label:"Pagona",img:""},
         {value:"Small_Frill",label:"Small Frill",img:""},

      ];

 export const Eyes =[
        // {value:"0" ,label:"ACUATIC CARDS", isDisabled:true},
        // {value: "Sleepless" ,label:"Sleepless"},
        // {value: "Gero" ,label:"Gero"},            
        // {value: "Clear", label:"Clear"},
         {value:"Telescope",label:"Telescope", img:"https://i.ibb.co/xL4500C/Telescope.png"},
        // {value : "1", label:"PLANT CARDS" , isDisabled:true},
        // {value: "Papi" ,label:"Papi" },
        // {value:"Confused",label:"Confused"},
        // {value:"Cucumber_Slice",label:"Cucumber Slice"},
        // {value:"Blossom",label:"Blossom "},
        // {value : "3", label:"BUG CARDS" , isDisabled:true},
        // {value: "Kotaro" ,label:"Kotaro" },
        // {value:"Neo",label:"Neo"},
        // {value:"Bookworm",label:"Bookworm"},
        // {value:"Nerdy",label:"Nerdy "},
        // {value : "4", label:"BEAST CARDS" , isDisabled:true},
        // {value: "Puppy" ,label:"Puppy" },
        // {value:"Little_Peas",label:"Little Peas"},
        // {value:"Chubby",label:"Chubby"},
        // {value:"Zeal",label:"Zeal "},
        // {value : "5", label:"BIRD CARDS" , isDisabled:true},
        {value: "Robin" ,label:"Robin" , img:"https://i.ibb.co/Gc32PXD/Robin.png"},
        // {value:"Mavis",label:"Mavis"},
        // {value:"Little_Owl",label:"Little Owl"},
        // {value:"Lucas",label:"Lucas "},
        // {value : "6", label:"REPTILE CARDS" , isDisabled:true},
        // {value: "Scar" ,label:"Scar" },
        // {value:"Topaz",label:"Topaz"},
        // {value:"Tricky",label:"Tricky"},
        // {value:"Gecko",label:"Gecko "},
        

      ];

 export const Mouth =[
   {value:"1", label:"ACUATIC CARDS", isDisabled:true},
   {value:"Lam", label:"Lam"},
   {value:"Risky_Fish", label:"Risky Fish", img:'https://i.ibb.co/5kpht6C/Risky-fish.png'},
   {value:"Piranha", label:"Piranha", img:'https://i.ibb.co/QKTMQQ8/Piranha.png'},
   {value:"Catfish", label:"Catfish"},
   {value:"2", label:"PLANT CARDS", isDisabled:true},
   {value:"Serious", label:"Serious"},
   {value:"Zigzag", label:"Zigzag"},
   {value:"Herbivore", label:"Herbivore"},
   {value:"Silence_Whisper", label:"Silence Whisper"},
   {value:"3", label:"BUG CARDS", isDisabled:true},
   {value:"Mosquito", label:"Mosquito"},
   {value:"Cute_Bunny", label:"Cute Bunny"},
   {value:"Pincer", label:"Pincer"},
   {value:"Square_Teeth", label:"Square Teeth"},
   {value:"4", label:"BEAST CARDS", isDisabled:true},
   {value:"Goda", label:"Goda"},
   {value:"Axie_Kiss", label:"Axie Kiss"},
   {value:"Confident", label:"Confident"},
   {value:"Nut_Cracker4", label:"Nut Cracker"},
   {value:"5", label:"BIRD CARDS", isDisabled:true},
   {value:"Little_Owl2", label:"Little Owl"},
   {value:"Doubletalk", label:"Doubletalk"},
   {value:"Hungry_Bird", label:"Hungry Bird"},
   {value:"Peace_Maker2", label:"Peace Maker"},
   {value:"6", label:"REPTILE CARDS", isDisabled:true},
   {value:"Kotaro", label:"Kotaro"},
   {value:"Tiny_Turtle", label:"Tiny Turtle"},
   {value:"Razor_Bite", label:"Razor Bite"},
   {value:"Toothless_Bite", label:"Toothless Bite"},

        ];

 export const Back =[
   {value:"1", label:"ACUATIC CARDS" ,isDisabled:true},
   {value:"Anemone",label:"Anemone"},
   {value:"Perch",label:"Perch"},
   {value:"Sponge",label:"Sponge"},
   {value:"Blue_Moon",label:"Blue Moon"},
   {value:"Hermit",label:"Hermit"},
   {value:"Goldfish",label:"Goldfish"},
   {value:"2", label:"PLANT CARDS" ,isDisabled:true},
   {value:"Turnip",label:"Turnip"},
   {value:"Shiitake",label:"Shiitake"},
   {value:"Mint",label:"Mint"},
   {value:"Pumpkin",label:"Pumpkin"},
   {value:"Watering_Can",label:"Watering Can"},
   {value:"Bidens",label:"Bidens"},
   {value:"3", label:"BUG CARDS" ,isDisabled:true},
   {value:"Sandal",label:"Sandal"},
   {value:"Garish_Worm",label:"Garish Worm"},
   {value:"Snail_Shell",label:"Snail Shell"},
   {value:"Buzz_Buzz",label:"Buzz Buzz"},
   {value:"Scarab",label:"Scarab"},
   {value:"Spiky_Wing",label:"Spiky Wing"},
   {value:"4", label:"BEAST CARDS" ,isDisabled:true},
   {value:"Ronin",label:"Ronin"},
   {value:"Jaguar",label:"Jaguar"},
   {value:"Hero",label:"Hero"},
   {value:"Risky_Beast",label:"Risky Beast"},
   {value:"Furball",label:"Furball"},
   {value:"Timber",label:"Timber"},
   {value:"5", label:"BIRD CARDS" ,isDisabled:true},
   {value:"Balloon",label:"Balloon"},
   {value:"Cupid",label:"Cupid"},
   {value:"Tri_Feather",label:"Tri Feather"},
   {value:"Kingfisher",label:"Kingfisher"},
   {value:"Raven",label:"Raven"},
   {value:"Pigeon_Post",label:"Pigeon Post"},
   {value:"6", label:"BIRD CARDS" ,isDisabled:true},
   {value:"Croc",label:"Croc"},
   {value:"Red_Ear",label:"Red Ear"},
   {value:"Indian_Star",label:"Indian Star"},
   {value:"Bone_Sail",label:"Bone Sail"},
   {value:"Tri_Spikes",label:"Tri Spikes"},
   {value:"Green_Thorns",label:"Green Thorns"},

 ];


 export const Horn =[
  {value:"1", label:"ACUATIC CARDS" ,isDisabled:true},
  {value: "Anemone2",label:"Anemone"},
  {value:"Shoal_Star",label:"Shoal Star"},
  {value: "Oranda",label:"Oranda"},
  {value:"Clamshell" ,label:"Clamshell"},
  {value:"Babylonia",label:"Babylonia"},
  { value:"Teal_Shell",label:"Teal Shell"},
  {value:"2", label:"PLANT CARDS" ,isDisabled:true},
  {value: "Beech",label:"Beech"},
  {value:"Rose_Bud",label:"Rose Bud"},
  {value: "Cactus",label:"Cactus"},
  {value:"Watermelon" ,label:"Watermelon"},
  {value:"Strawberry_Shortcake",label:"Strawberry Shortcake"},
  { value:"Bamboo_Shoot",label:"Bamboo Shoot"},
  {value:"3", label:"BUG CARDS" ,isDisabled:true},
  {value: "Lagging",label:"Lagging"},
  {value:"Antenna",label:"Antenna"},
  {value: "Leaf_Bug2",label:"Leaf Bug"},
  {value:"Parasite" ,label:"Parasite"},
  {value:"Pliers",label:"Pliers"},
  { value:"Caterpillars",label:"Caterpillars"},
  {value:"4", label:"BEAST CARDS" ,isDisabled:true},
  {value: "Arco",label:"Arco"},
  {value:"Dual_Blade",label:"Dual Blade"},
  {value: "Pocky",label:"Pocky"},
  {value:"Imp" ,label:"Imp"},
  {value:"Merry",label:"Merry"},
  { value:"Little_Branch",label:"Little Branch"},
  {value:"5", label:"BIRD CARDS" ,isDisabled:true},
  {value: "Eggshell",label:"Eggshell"},
  {value:"Cuckoo",label:"Cuckoo"},
  {value: "Trump",label:"Trump"},
  {value:"Feather_Spear" ,label:"Feather Spear"},
  {value:"Kestrel",label:"Kestrel"},
  { value:"Wing_Horn",label:"Wing Horn"},
  {value:"6", label:"REPTILE CARDS" ,isDisabled:true},
  {value: "Bumpy",label:"Bumpy"},
  {value:"Scaly_Spoon",label:"Scaly Spoon"},
  {value: "Cerastes",label:"Cerastes"},
  {value:"Unko" ,label:"Unko"},
  {value:"Scaly_Spear",label:"Scaly Spear"},
  { value:"Incisor",label:"Incisor"},

        ];

export const Tail =[
   {value:"1" ,label:"ACUATIC CARDS", isDisabled:true},
   { value: 'Nimo' , label: ' Nimo' , img:'https://i.ibb.co/HKLGqzH/Nimo.png'},
   { value: 'Shrimp', label: ' Shrimp' },           
   { value: 'Navaga', label: ' Navaga' },
   { value: 'Koi', label: ' Koi' , img:'https://i.ibb.co/Q9FbGj1/Koi.png'},
   { value: 'Tadpole', label: ' Tadpole' },
   { value: 'Ranchu', label: ' Ranchu' },
   {value:"2" ,label:"PLANT CARDS", isDisabled:true},
   { value: 'Cattail' , label: ' Cattail' },
   { value: 'Hatsune', label: ' Hatsune' },           
   { value: 'Carrot', label: ' Carrot' },
   { value: 'Yam', label: ' Yam' },
   { value: 'Potato_Leaf', label: ' Potato Leaf' },
   { value: 'Hot_Butt', label: ' Hot Butt' },
   {value:"3" ,label:"BUG CARDS", isDisabled:true},
   { value: 'Fish_Snack' , label: ' Fish Snack' },
   { value: 'Ant', label: ' Ant' },           
   { value: 'Pupae', label: ' Pupae' },
   { value: 'Twin_Tail', label: ' Twin Tail' },
   { value: 'Gravel_Ant', label: ' Gravel Ant' },
   { value: 'Thorny_Caterpillar', label: ' Thorny Caterpillar' },
   {value:"4" ,label:"BEAST CARDS", isDisabled:true},
   { value: 'Nut_Cracker' , label: ' Nut Cracker' },
   { value: 'Shiba', label: ' Shiba' },           
   { value: 'Gerbil', label: ' Gerbil' },
   { value: 'Hare', label: ' Hare' },
   { value: 'Rice', label: ' Rice' },
   { value: 'Cottontail', label: ' Cottontail' },
   {value:"5" ,label:"BIRD CARDS", isDisabled:true},
   { value: 'Swallow' , label: ' Swallow' },
   { value: 'Post_Fight', label: ' Post Fight' },           
   { value: 'Cloud', label: ' Cloud' },
   { value: 'Granmas_Fan', label: ' Granmas Fan' },
   { value: 'Feather_Fan', label: ' Feather Fan' },
   { value: 'The_Last_One', label: ' The Last One' },
   {value:"6" ,label:"REPTILE CARDS", isDisabled:true},
   { value: 'Wall_Gecko' , label: ' Wall Gecko' },
   { value: 'Iguana', label: ' Iguana' },           
   { value: 'Snake_Jar', label: ' Snake Jar' },
   { value: 'Gila', label: ' Gila' },
   { value: 'Grass_Snake', label: ' Grass Snake' },
   { value: 'Tiny_Dino', label: ' Tiny Dino' },
   ]


